<?php

return [
    'progress' => [
        ['id' => 'hook', 'label' => 'Inicio'],
        ['id' => 'aprender', 'label' => 'Formación'],
        ['id' => 'ingreso', 'label' => 'Ingreso'],
        ['id' => 'egreso', 'label' => 'Egreso'],
        ['id' => 'comienza', 'label' => 'Admisión'],
    ],

    'scenes' => [
        [
            'id' => 'hook',
            'number' => '01',
            'eyebrow' => 'Facultad de Criminología',
            'title' => '¿Por qué estudiar Criminología?',
            'description' => 'Comprende las causas del delito, apoya la seguridad ciudadana y contribuye a una sociedad más justa con análisis científico y compromiso ético.',
            'image' => 'images/criminologia/9bce3a38-cc9c-472f-97a1-500a2abc54b8.png',
            'image_alt' => 'Sesión académica de Criminología en UMG Guastatoya',
            'image_position' => '50% 42%',
            'variant' => 'hook',
            'nav_label' => 'Inicio',
            'points' => [
                'Investigar y prevenir fenómenos delictivos',
                'Trabajar en justicia y seguridad pública',
                'Formación ética con enfoque humano',
            ],
        ],
        [
            'id' => 'aprender',
            'number' => '02',
            'eyebrow' => 'La carrera en síntesis',
            'title' => '¿Qué aprenderás?',
            'description' => 'Analiza el delito con creatividad, lógica crítica y base en psicología criminal, criminalística y marco jurídico.',
            'image' => 'images/criminologia/12423ea1-ce43-48ca-9cc6-ae42c184bb65.png',
            'image_alt' => 'Espacio de estudio con herramientas de análisis criminológico',
            'image_position' => '48% 40%',
            'variant' => 'aprender',
            'nav_label' => 'Formación',
            'words' => ['ANALIZAR', 'COMPRENDER', 'PREVENIR'],
            'points' => [
                'Criminología, criminalística y victimología',
                'Psicología criminal y derecho penal',
                'Investigación, perfiles y prevención',
            ],
        ],
        [
            'id' => 'ingreso',
            'number' => '03',
            'eyebrow' => 'UMG Guastatoya',
            'title' => 'Perfil de ingreso',
            'description' => 'Buscamos aspirantes con habilidad investigativa, pensamiento crítico e interés por el comportamiento humano y la justicia.',
            'image' => 'images/criminologia/628403d8-a6e7-4f4f-97d0-2fa24030336f.png',
            'image_alt' => 'Fachada de la Facultad de Criminología UMG',
            'image_position' => '50% 45%',
            'variant' => 'ingreso',
            'nav_label' => 'Ingreso',
            'points' => [
                'Lógica e investigación de problemas sociales',
                'Compromiso ético con el marco legal',
                'Comunicación efectiva y ciencias sociales',
            ],
        ],
        [
            'id' => 'egreso',
            'number' => '04',
            'eyebrow' => 'Criminología con propósito',
            'title' => 'Perfil de egreso',
            'description' => 'Egresarás listo para investigar, prevenir y diseñar estrategias de seguridad y reinserción dentro del marco legal.',
            'image' => 'images/criminologia/86e65f4f-48b9-4eee-beb6-a789569cb799.png',
            'image_alt' => 'Laboratorio de criminalística UMG Guastatoya',
            'image_position' => '52% 40%',
            'variant' => 'egreso',
            'nav_label' => 'Egreso',
            'points' => [
                'Investigación criminal y forense',
                'Perfilación y análisis de conducta',
                'Seguridad, prevención y reinserción social',
            ],
        ],
        [
            'id' => 'comienza',
            'number' => '05',
            'eyebrow' => 'Admisión abierta',
            'title' => 'Tu historia puede empezar aquí',
            'description' => 'Licenciatura en Criminología y Política Criminal. Inscríbete en UMG Guastatoya y aporta a una sociedad más segura.',
            'image' => 'images/criminologia/330d0b41-7291-40e9-a726-545c32ae3b68.png',
            'image_alt' => 'Espacio profesional de Criminología con branding UMG',
            'image_position' => '45% 42%',
            'variant' => 'comienza',
            'nav_label' => 'Admisión',
            'points' => [
                'Docentes especializados y enfoque práctico',
                'Plan orientado a investigación y prevención',
            ],
            'ctas' => [
                [
                    'label' => 'Ver pensum',
                    'href' => '#umg-criminologia-pensum',
                    'style' => 'ghost',
                ],
                [
                    'label' => 'Inscribirme',
                    'href' => 'https://umg.edu.gt/admisiones',
                    'style' => 'primary',
                    'external' => true,
                ],
            ],
        ],
    ],
];
