<?php

return [
    'progress' => [
        ['id' => 'hook', 'label' => 'Inicio'],
        ['id' => 'facultad', 'label' => 'Facultad'],
        ['id' => 'formacion', 'label' => 'Formación'],
        ['id' => 'experiencia', 'label' => 'Práctica'],
        ['id' => 'futuro', 'label' => 'Futuro'],
        ['id' => 'comienza', 'label' => 'Admisión'],
    ],

    'scenes' => [
        [
            'id' => 'hook',
            'number' => '01',
            'eyebrow' => 'Ciencias Jurídicas y Sociales',
            'title' => '¿Listo para defender tus ideas?',
            'description' => 'Tu voz puede convertirse en una herramienta de transformación.',
            'image' => 'build/img/about/iniDerecho1.jpg',
            'image_alt' => 'Estudiante de Derecho en un entorno académico',
            'variant' => 'hook',
            'nav_label' => 'Inicio',
        ],
        [
            'id' => 'facultad',
            'number' => '02',
            'eyebrow' => 'UMG Guastatoya',
            'title' => 'Facultad de Derecho',
            'description' => 'Formamos juristas capaces de comprender, interpretar y transformar su entorno.',
            'image' => 'build/img/about/iniDerecho.jpg',
            'image_alt' => 'Ambiente académico de la Facultad de Derecho',
            'variant' => 'facultad',
            'nav_label' => 'Facultad',
        ],
        [
            'id' => 'formacion',
            'number' => '03',
            'eyebrow' => 'Pensamiento jurídico',
            'title' => 'Argumentos que cambian decisiones',
            'description' => 'Aprende a construir razonamientos sólidos en el aula y en la práctica.',
            'image' => 'build/img/index/congresoderecho.jpeg',
            'image_alt' => 'Debate y argumentación en la formación jurídica',
            'variant' => 'formacion',
            'nav_label' => 'Formación',
            'words' => ['COMPRENDER', 'ARGUMENTAR', 'DEFENDER'],
        ],
        [
            'id' => 'experiencia',
            'number' => '04',
            'eyebrow' => 'Experiencia universitaria',
            'title' => 'El Derecho se practica',
            'description' => 'Casos, debates, investigación y simulaciones que acercan el aula a la realidad.',
            'image' => 'build/img/about/pabellonUMG.jpeg',
            'image_alt' => 'Campus UMG Guastatoya',
            'variant' => 'experiencia',
            'nav_label' => 'Práctica',
        ],
        [
            'id' => 'futuro',
            'number' => '05',
            'eyebrow' => 'Trayectoria profesional',
            'title' => 'Muchos caminos. Una vocación.',
            'description' => 'Elige el área donde quieres influir con el Derecho.',
            'image' => 'build/img/index/EstudiantesU.png',
            'image_alt' => 'Estudiantes universitarios UMG',
            'variant' => 'futuro',
            'nav_label' => 'Futuro',
            'paths' => [
                'Derecho Corporativo',
                'Derecho Penal',
                'Derecho Civil',
                'Derecho Internacional',
                'Sector Público',
                'Consultoría Jurídica',
            ],
        ],
        [
            'id' => 'comienza',
            'number' => '06',
            'eyebrow' => 'Admisión abierta',
            'title' => 'Tu historia puede empezar aquí',
            'description' => 'Conoce la carrera e inscríbete en la Facultad de Derecho UMG Guastatoya.',
            'image' => 'build/img/about/iniDerecho1.jpg',
            'image_alt' => 'Inicio de la carrera de Derecho en UMG',
            'variant' => 'comienza',
            'nav_label' => 'Admisión',
            'ctas' => [
                [
                    'label' => 'Conocer la carrera',
                    'href' => '#umg-derecho-features',
                    'style' => 'ghost',
                ],
                [
                    'label' => 'Inscribirme',
                    'href' => 'https://umg.edu.gt/admisiones',
                    'style' => 'primary',
                    'external' => true,
                ],
            ],
        ],
    ],
];
