<?php

return [
    'progress' => [
        ['id' => 'hook', 'label' => 'Inicio'],
        ['id' => 'aprender', 'label' => 'Formación'],
        ['id' => 'ingreso', 'label' => 'Ingreso'],
        ['id' => 'egreso', 'label' => 'Egreso'],
        ['id' => 'comienza', 'label' => 'Admisión'],
    ],

    'scenes' => [
        [
            'id' => 'hook',
            'number' => '01',
            'eyebrow' => 'Facultad de Auditoría',
            'title' => '¿Por qué estudiar Contaduría y Auditoría?',
            'description' => 'Analiza, verifica y genera confianza. Tu criterio ético puede fortalecer organizaciones y aportar transparencia al entorno económico.',
            'image' => 'images/Auditoria/c61132ca-a3a6-4d14-afe4-d5b2969e971f.png',
            'image_alt' => 'Espacio de trabajo de Auditoría UMG con herramientas de análisis',
            'image_position' => '55% 45%',
            'variant' => 'hook',
            'nav_label' => 'Inicio',
            'points' => [
                'Gestionar y auditar información financiera',
                'Campo laboral estable en sector público y privado',
                'Formación ética con visión global',
            ],
        ],
        [
            'id' => 'aprender',
            'number' => '02',
            'eyebrow' => 'La carrera en síntesis',
            'title' => '¿Qué aprenderás?',
            'description' => 'Resuelve problemas empresariales y toma decisiones contables y financieras con normativas internacionales y herramientas tecnológicas.',
            'image' => 'images/Auditoria/0f3e518f-9f09-4791-8e81-2ad66cdfd3f6.png',
            'image_alt' => 'Informe de auditoría y materiales de estudio UMG',
            'image_position' => '48% 42%',
            'variant' => 'aprender',
            'nav_label' => 'Formación',
            'words' => ['ANALIZAR', 'EVALUAR', 'VERIFICAR'],
            'points' => [
                'Contabilidad, costos y finanzas',
                'Normas internacionales y control interno',
                'Auditoría, riesgos y ética profesional',
            ],
        ],
        [
            'id' => 'ingreso',
            'number' => '03',
            'eyebrow' => 'UMG Guastatoya',
            'title' => 'Perfil de ingreso',
            'description' => 'Buscamos personas con interés contable, habilidades numéricas, razonamiento crítico y dedicación para asesorar con rigor.',
            'image' => 'images/Auditoria/52fb461f-4dd3-4912-abe6-42f9cb39108d.png',
            'image_alt' => 'Escritorio de auditoría con checklist de objetividad e integridad',
            'image_position' => '50% 40%',
            'variant' => 'ingreso',
            'nav_label' => 'Ingreso',
            'points' => [
                'Habilidad numérica y pensamiento analítico',
                'Comprensión lectora y solución de problemas',
                'Compromiso con la ética y la transparencia',
            ],
        ],
        [
            'id' => 'egreso',
            'number' => '04',
            'eyebrow' => 'Auditoría con propósito',
            'title' => 'Perfil de egreso',
            'description' => 'Egresarás como profesional ético e independiente, listo para decidir en contabilidad, finanzas, auditoría y tecnología.',
            'image' => 'images/Auditoria/f9b81e2c-a42c-4e4d-9726-69b5f92aaee2.png',
            'image_alt' => 'Planificación de auditoría con valores de transparencia y confianza',
            'image_position' => '52% 38%',
            'variant' => 'egreso',
            'nav_label' => 'Egreso',
            'points' => [
                'Auditoría interna/externa y consultoría',
                'Dirección financiera y asesoría tributaria',
                'Control interno y gestión de riesgos',
            ],
        ],
        [
            'id' => 'comienza',
            'number' => '05',
            'eyebrow' => 'Admisión abierta',
            'title' => 'Tu historia puede empezar aquí',
            'description' => 'Licenciatura en Contaduría Pública y Auditoría. Inscríbete en UMG Guastatoya y forma parte de una profesión de confianza.',
            'image' => 'images/Auditoria/d84542fa-6be8-457b-a58a-4f4ac7b09a8c.png',
            'image_alt' => 'Espacio de estudio de Auditoría con vista al campus UMG',
            'image_position' => '45% 40%',
            'variant' => 'comienza',
            'nav_label' => 'Admisión',
            'points' => [
                'Docentes con experiencia profesional',
                'Plan actualizado orientado a la práctica',
            ],
            'ctas' => [
                [
                    'label' => 'Ver pensum',
                    'href' => '#umg-auditoria-pensum',
                    'style' => 'ghost',
                ],
                [
                    'label' => 'Inscribirme',
                    'href' => 'https://umg.edu.gt/admisiones',
                    'style' => 'primary',
                    'external' => true,
                ],
            ],
        ],
    ],
];
