<?php

return [
    'progress' => [
        ['id' => 'hook', 'label' => 'Inicio'],
        ['id' => 'aprender', 'label' => 'Formación'],
        ['id' => 'ingreso', 'label' => 'Ingreso'],
        ['id' => 'egreso', 'label' => 'Egreso'],
        ['id' => 'comienza', 'label' => 'Admisión'],
    ],

    'scenes' => [
        [
            'id' => 'hook',
            'number' => '01',
            'eyebrow' => 'Facultad de Ciencias Jurídicas y Sociales',
            'title' => '¿Por qué estudiar Derecho?',
            'description' => 'Tu voz puede convertirse en una herramienta de transformación. Defiende derechos, resuelve conflictos y construye una sociedad más justa.',
            'image' => 'images/derecho/dae92492-c3b6-40b3-b0db-fef76501688c.png',
            'image_alt' => 'Símbolos de la justicia: estatua, mazo y libros de derecho',
            'image_position' => '58% 46%',
            'variant' => 'hook',
            'nav_label' => 'Inicio',
            'points' => [
                'Defender derechos y resolver conflictos',
                'Incidir en lo público y lo privado',
                'Formación con ética y compromiso social',
            ],
        ],
        [
            'id' => 'aprender',
            'number' => '02',
            'eyebrow' => 'La carrera en síntesis',
            'title' => '¿Qué aprenderás?',
            'description' => 'Interpretar, aplicar y defender el Derecho con bases firmes en las ramas fundamentales y capacidad de argumentación.',
            'image' => 'images/derecho/202e91d8-e0b5-4ce4-8e69-132cbd907ea8.png',
            'image_alt' => 'Catedrático y estudiantes de Derecho en una sesión de formación',
            'image_position' => '48% 38%',
            'variant' => 'aprender',
            'nav_label' => 'Formación',
            'words' => ['COMPRENDER', 'ARGUMENTAR', 'DEFENDER'],
            'points' => [
                'Constitucional, Civil, Penal y Laboral',
                'Administrativo, Procesal y Notarial',
                'Pensamiento crítico y razonamiento lógico',
            ],
        ],
        [
            'id' => 'ingreso',
            'number' => '03',
            'eyebrow' => 'UMG Guastatoya',
            'title' => 'Perfil de ingreso',
            'description' => 'Buscamos aspirantes con análisis, pensamiento crítico e interés por lo social, listos para comunicar con claridad.',
            'image' => 'images/derecho/c54973a6-28e3-4cb2-9ed0-1198dc5ef71a.png',
            'image_alt' => 'Fachada de la Facultad de Derecho UMG Guastatoya',
            'image_position' => '50% 42%',
            'variant' => 'ingreso',
            'nav_label' => 'Ingreso',
            'points' => [
                'Vocación de servicio y compromiso ético',
                'Interés por instituciones y procesos sociales',
                'Competencias: interpretación, redacción y análisis',
            ],
        ],
        [
            'id' => 'egreso',
            'number' => '04',
            'eyebrow' => 'Derecho con propósito',
            'title' => 'Perfil de egreso',
            'description' => 'Egresarás capaz de asesorar, representar y resolver conflictos con responsabilidad social y dominio profesional.',
            'image' => 'images/derecho/286a5444-fe87-4309-9c91-2dcc0a87f7c3.png',
            'image_alt' => 'Sala de audiencias con ambiente jurídico profesional',
            'image_position' => '50% 44%',
            'variant' => 'egreso',
            'nav_label' => 'Egreso',
            'points' => [
                'Litigio, asesoría y notariado',
                'Resolución de conflictos y derechos humanos',
                'Casos, debates y práctica cercana a la realidad',
            ],
        ],
        [
            'id' => 'comienza',
            'number' => '05',
            'eyebrow' => 'Admisión abierta',
            'title' => 'Tu historia puede empezar aquí',
            'description' => 'Licenciatura en Ciencias Jurídicas y Sociales, Abogacía y Notariado. Inscríbete en UMG Guastatoya.',
            'image' => 'images/derecho/13114088-8b42-464f-bffc-23800f858e14.png',
            'image_alt' => 'Estudiante de Derecho en un entorno de estudio profesional',
            'image_position' => '32% 36%',
            'variant' => 'comienza',
            'nav_label' => 'Admisión',
            'points' => [
                'Docentes especializados y enfoque práctico',
                'Plan actualizado orientado al ejercicio profesional',
            ],
            'ctas' => [
                [
                    'label' => 'Ver pensum',
                    'href' => '#umg-derecho-pensum',
                    'style' => 'ghost',
                ],
                [
                    'label' => 'Inscribirme',
                    'href' => 'https://umg.edu.gt/admisiones',
                    'style' => 'primary',
                    'external' => true,
                ],
            ],
        ],
    ],
];
