<?php

return [
    'progress' => [
        ['id' => 'hook', 'label' => 'Inicio'],
        ['id' => 'aprender', 'label' => 'Formación'],
        ['id' => 'ingreso', 'label' => 'Ingreso'],
        ['id' => 'egreso', 'label' => 'Egreso'],
        ['id' => 'comienza', 'label' => 'Admisión'],
    ],

    'scenes' => [
        [
            'id' => 'hook',
            'number' => '01',
            'eyebrow' => 'Facultad de Sistemas',
            'title' => '¿Por qué estudiar Ingeniería en Sistemas?',
            'description' => 'Conecta ideas, crea soluciones y transforma el mundo digital. Es una de las carreras con mayor demanda en software, redes, IA y ciberseguridad.',
            'image' => 'images/sistemas/e46e809b-4460-4c58-a907-c2d710742705.png',
            'image_alt' => 'Estudiante de Sistemas UMG desarrollando software',
            'image_position' => '50% 35%',
            'variant' => 'hook',
            'nav_label' => 'Inicio',
            'points' => [
                'Oportunidades globales en tecnología',
                'Innovar, desarrollar y transformar',
                'Formación práctica con impacto real',
            ],
        ],
        [
            'id' => 'aprender',
            'number' => '02',
            'eyebrow' => 'La carrera en síntesis',
            'title' => '¿Qué aprenderás?',
            'description' => 'Desarrolla software, administra sistemas y bases de datos, implementa redes y gestiona proyectos tecnológicos para el sector público y privado.',
            'image' => 'images/sistemas/5d9ba46e-80dd-4ce9-b15f-98650ccd1e16.png',
            'image_alt' => 'Espacio de estudio con programación y libros de Sistemas UMG',
            'image_position' => '48% 40%',
            'variant' => 'aprender',
            'nav_label' => 'Formación',
            'words' => ['DESARROLLA', 'CREA', 'CONECTA'],
            'points' => [
                'Programación, bases de datos y redes',
                'Ingeniería de software y sistemas operativos',
                'Telecomunicaciones y gestión de proyectos',
            ],
        ],
        [
            'id' => 'ingreso',
            'number' => '03',
            'eyebrow' => 'UMG Guastatoya',
            'title' => 'Perfil de ingreso',
            'description' => 'Buscamos aspirantes con base en matemáticas, interés genuino por la tecnología y disposición para aprender y actualizarse de forma constante.',
            'image' => 'images/sistemas/7a38f1d4-d60a-4cfd-8a28-b60116dd8736.png',
            'image_alt' => 'Laboratorio de Ingeniería en Sistemas UMG',
            'image_position' => '50% 42%',
            'variant' => 'ingreso',
            'nav_label' => 'Ingreso',
            'points' => [
                'Sólida base matemática y lógica',
                'Capacidad de resolver problemas',
                'Adaptabilidad ante nuevas tecnologías',
            ],
        ],
        [
            'id' => 'egreso',
            'number' => '04',
            'eyebrow' => 'Sistemas con propósito',
            'title' => 'Perfil de egreso',
            'description' => 'Egresarás listo para diseñar, implementar y gestionar proyectos tecnológicos complejos con calidad, eficiencia y visión global.',
            'image' => 'images/sistemas/c069011d-fb93-44ca-b3ce-ba8a72e4c16e.png',
            'image_alt' => 'Ingeniero en Sistemas trabajando en estación multi-monitor',
            'image_position' => '52% 38%',
            'variant' => 'egreso',
            'nav_label' => 'Egreso',
            'points' => [
                'Algoritmos, bases de datos y redes',
                'Desarrollo de software e infraestructura',
                'Liderazgo en transformación digital',
            ],
        ],
        [
            'id' => 'comienza',
            'number' => '05',
            'eyebrow' => 'Admisión abierta',
            'title' => 'Tu historia puede empezar aquí',
            'description' => 'Ingeniería en Sistemas de Información y Ciencias de la Computación. Inscríbete en UMG Guastatoya y construye tecnología con valores.',
            'image' => 'images/sistemas/5d9ba46e-80dd-4ce9-b15f-98650ccd1e16.png',
            'image_alt' => 'Tecnología que construye oportunidades — Facultad de Sistemas UMG',
            'image_position' => '45% 42%',
            'variant' => 'comienza',
            'nav_label' => 'Admisión',
            'points' => [
                'Docentes especializados y laboratorios actualizados',
                'Plan orientado a la industria tecnológica',
            ],
            'ctas' => [
                [
                    'label' => 'Ver pensum',
                    'href' => '#umg-sistemas-pensum',
                    'style' => 'ghost',
                ],
                [
                    'label' => 'Inscribirme',
                    'href' => 'https://umg.edu.gt/admisiones',
                    'style' => 'primary',
                    'external' => true,
                ],
            ],
        ],
    ],
];
