<?php

return [
    'progress' => [
        ['id' => 'hook', 'label' => 'Inicio'],
        ['id' => 'aprender', 'label' => 'Formación'],
        ['id' => 'ingreso', 'label' => 'Ingreso'],
        ['id' => 'egreso', 'label' => 'Egreso'],
        ['id' => 'comienza', 'label' => 'Admisión'],
    ],

    'scenes' => [
        [
            'id' => 'hook',
            'number' => '01',
            'eyebrow' => 'Facultad de Administración',
            'title' => '¿Por qué estudiar Administración?',
            'description' => 'Lidera equipos, toma decisiones con datos y transforma organizaciones. Tu visión estratégica puede impulsar empresas y comunidades.',
            'image' => 'images/administracion/0301dac5-e4ca-4e7b-abb2-a9900cf98c12.png',
            'image_alt' => 'Sesión colaborativa de Administración en UMG Guastatoya',
            'image_position' => '50% 42%',
            'variant' => 'hook',
            'nav_label' => 'Inicio',
            'points' => [
                'Dirigir empresas y gestionar el cambio',
                'Decidir con análisis financiero y operativo',
                'Formación ética con visión global',
            ],
        ],
        [
            'id' => 'aprender',
            'number' => '02',
            'eyebrow' => 'La carrera en síntesis',
            'title' => '¿Qué aprenderás?',
            'description' => 'Combina teoría y práctica para dirigir con solidez: finanzas, mercadeo, operaciones, talento humano y estrategia.',
            'image' => 'images/administracion/e9b2710a-e49d-4502-8d69-a531a56f9d90.png',
            'image_alt' => 'Escritorio de estudio con materiales de Administración UMG',
            'image_position' => '48% 40%',
            'variant' => 'aprender',
            'nav_label' => 'Formación',
            'words' => ['PLANEAR', 'LIDERAR', 'CRECER'],
            'points' => [
                'Dirección, contabilidad y finanzas',
                'Mercadeo, operaciones y logística',
                'Talento humano y toma de decisiones',
            ],
        ],
        [
            'id' => 'ingreso',
            'number' => '03',
            'eyebrow' => 'UMG Guastatoya',
            'title' => 'Perfil de ingreso',
            'description' => 'Buscamos aspirantes con pensamiento analítico, interés por las organizaciones y ganas de liderar con trabajo en equipo.',
            'image' => 'images/administracion/fb7a73b4-8292-4539-aff7-b9200dbada1b.png',
            'image_alt' => 'Fachada de la Facultad de Administración UMG',
            'image_position' => '50% 45%',
            'variant' => 'ingreso',
            'nav_label' => 'Ingreso',
            'points' => [
                'Pensamiento estratégico y proactivo',
                'Comunicación y colaboración',
                'Adaptabilidad ante entornos cambiantes',
            ],
        ],
        [
            'id' => 'egreso',
            'number' => '04',
            'eyebrow' => 'Administración con propósito',
            'title' => 'Perfil de egreso',
            'description' => 'Egresarás listo para dirigir, asesorar y emprender con ética, visión estratégica y dominio de la gestión empresarial.',
            'image' => 'images/administracion/f8853cef-74d2-424f-9465-56a812b6c4d7.png',
            'image_alt' => 'Sala de reuniones con plan estratégico de Administración',
            'image_position' => '52% 40%',
            'variant' => 'egreso',
            'nav_label' => 'Egreso',
            'points' => [
                'Cargos directivos, financieros y comerciales',
                'Liderazgo de equipos y gestión del cambio',
                'Emprendimiento con responsabilidad social',
            ],
        ],
        [
            'id' => 'comienza',
            'number' => '05',
            'eyebrow' => 'Admisión abierta',
            'title' => 'Tu historia puede empezar aquí',
            'description' => 'Licenciatura en Ciencias de la Administración. Inscríbete en UMG Guastatoya y lidera el futuro de las organizaciones.',
            'image' => 'images/administracion/a7790aec-ac37-467f-ac56-f0fe0045e2dd.png',
            'image_alt' => 'Espacio de trabajo con análisis de gestión UMG',
            'image_position' => '45% 42%',
            'variant' => 'comienza',
            'nav_label' => 'Admisión',
            'points' => [
                'Docentes con experiencia profesional',
                'Plan actualizado orientado a la práctica',
            ],
            'ctas' => [
                [
                    'label' => 'Ver pensum',
                    'href' => '#umg-administracion-pensum',
                    'style' => 'ghost',
                ],
                [
                    'label' => 'Inscribirme',
                    'href' => 'https://umg.edu.gt/admisiones',
                    'style' => 'primary',
                    'external' => true,
                ],
            ],
        ],
    ],
];
