<?php

return [
    'derecho' => [
        'slug' => 'derecho',
        'eyebrow' => 'Facultad de Ciencias Jurídicas y Sociales',
        'title' => 'Derecho',
        'subtitle' => 'Ciencias Jurídicas y Sociales',
        'lead' => 'Licenciatura en Ciencias Jurídicas y Sociales. Formación jurídica integral con visión ética, práctica y compromiso social.',
        'title_label' => 'Título',
        'degree' => 'Licenciatura en Ciencias Jurídicas y Sociales',
        'duration' => '5 años',
        'hero_image' => 'build/img/about/iniDerecho1.jpg',
        'hero_alt' => 'Estudiantes y formación en la Facultad de Derecho UMG Guastatoya',
        'intro_paragraphs' => [
            'La carrera de Ciencias Jurídicas y Sociales entrelaza el estudio del derecho con las ciencias sociales, enfatizando la interpretación y aplicación legal en contextos variados. El aprendizaje se basa en el análisis de casos, el debate crítico y la práctica en clínicas jurídicas.',
            'Se cultiva la habilidad argumentativa y el razonamiento ético para abordar asuntos de justicia social. La formación se orienta hacia la conciencia social y el desarrollo humano en la práctica legal. El objetivo es formar juristas con visión integral, capaces de influir positivamente en la sociedad.',
        ],
        'quote' => 'Y conoceréis la verdad y la verdad os hará libres',
        'intro_image' => 'build/img/about/iniDerecho.jpg',
        'intro_alt' => 'Ambiente académico de la Facultad de Derecho',
        'features_eyebrow' => 'UMG Guastatoya',
        'features_title' => 'Desarrolla tu potencial y lidera en tu profesión',
        'features_lead' => 'La Licenciatura en Ciencias Jurídicas y Sociales, Abogacía y Notariado de la Universidad Mariano Gálvez de Guatemala te prepara para comprender, interpretar y aplicar el Derecho con la guía de profesionales expertos en el ámbito jurídico.',
        'features' => [
            [
                'num' => '01',
                'title' => '¿Qué aprenderás?',
                'body' => 'Adquirirás una sólida formación teórica y práctica para la interpretación, aplicación y defensa del derecho. Desarrollarás pensamiento crítico, razonamiento lógico y capacidad argumentativa para analizar problemas jurídicos complejos. El plan de estudios te proporcionará bases firmes en Derecho Constitucional, Civil, Penal, Laboral, Administrativo y Notarial, garantizando que puedas actuar siempre dentro del marco legal y con responsabilidad profesional.',
            ],
            [
                'num' => '02',
                'title' => 'Perfil de ingreso',
                'body' => 'El aspirante ideal debe poseer habilidades de análisis, pensamiento crítico y razonamiento lógico. Debe mostrar interés por los procesos sociales, el comportamiento humano y el funcionamiento de las instituciones del Estado. Asimismo, es esencial que tenga vocación de servicio, compromiso ético, responsabilidad social y facilidad para comunicarse de manera oral y escrita.',
            ],
            [
                'num' => '03',
                'title' => 'Perfil de egreso',
                'body' => 'El egresado será un profesional capaz de interpretar y aplicar la legislación vigente, asesorar legalmente, representar a personas ante distintas instancias judiciales y elaborar instrumentos notariales. Contará con dominio de las ramas fundamentales del derecho, capacidad para la argumentación jurídica, habilidades para la resolución de conflictos y un sólido compromiso ético.',
            ],
        ],
        'topics_eyebrow' => 'Facultad de Ciencias Jurídicas y Sociales',
        'topics_title' => 'Derecho con propósito',
        'topics_lead' => 'Es la disciplina que interpreta, aplica y desarrolla el ordenamiento jurídico, utilizando conocimientos en legislación, argumentación, análisis crítico y redacción legal para resolver conflictos, garantizar la justicia y atender las necesidades sociales dentro del marco del Derecho.',
        'topics' => [
            [
                'title' => '¿Por qué estudiar Derecho?',
                'body' => 'Permite defender derechos, resolver conflictos, participar en la construcción de una sociedad más justa y acceder a múltiples oportunidades profesionales en el sector público y privado.',
                'image' => 'build/img/about/iniDerecho1.jpg',
            ],
            [
                'title' => 'El futuro del Derecho',
                'body' => 'La práctica jurídica evoluciona con la digitalización, el gobierno electrónico y la gestión moderna de información legal, generando nuevas áreas de especialización.',
                'image' => 'build/img/about/pabellonUMG.jpeg',
            ],
            [
                'title' => 'Competencias clave',
                'body' => 'Interpretación de normas, argumentación jurídica, redacción legal, análisis crítico y uso adecuado de herramientas tecnológicas aplicadas al ámbito jurídico.',
                'image' => 'build/img/about/iniDerecho.jpg',
            ],
            [
                'title' => 'Responsabilidad social',
                'body' => 'El profesional del Derecho contribuye al bienestar social garantizando justicia, respeto a los derechos humanos y soluciones legales que fortalezcan la convivencia y el orden jurídico.',
                'image' => 'build/img/index/EstudiantesU.png',
            ],
        ],
        'instructors_title' => 'Nuestros catedráticos',
        'instructors' => [
            [
                'name' => 'Licda. Susan Eunice Galindo Catalan',
                'role' => 'Licenciada en Ciencias Jurídicas y Sociales',
                'image' => 'build/img/instructor/docenteCrimi3.png',
                'route' => 'detalles-instructor-derecho1',
                'muted' => false,
            ],
            [
                'name' => 'Licda. Falvio Arturon',
                'role' => 'Licenciado en Ciencias Jurídicas y Sociales',
                'image' => 'build/img/instructor/1.png',
                'route' => 'detalles-instructor-derecho2',
                'muted' => false,
            ],
            [
                'name' => 'En construcción',
                'role' => 'Perfil próximamente',
                'image' => 'build/img/instructor/unknown_user.png',
                'route' => null,
                'muted' => true,
            ],
        ],
        'stats' => [
            ['value' => 10, 'label' => 'Oportunidades laborales'],
            ['value' => 6, 'label' => 'Catedráticos'],
            ['value' => 25, 'label' => 'Cursos certificados'],
            ['value' => 8, 'label' => 'Salones de clases'],
        ],
        'faq_image' => 'build/img/about/pabellonUMG.jpeg',
        'faq' => [
            [
                'q' => '¿Por qué elegirnos para tu educación?',
                'a' => 'Porque ofrecemos una formación jurídica integral, con docentes especializados, enfoque práctico, valores éticos y un plan de estudios actualizado que prepara a los futuros profesionales para desempeñarse con excelencia en cualquier área del Derecho.',
                'list' => null,
            ],
            [
                'q' => '¿Qué cursos contiene la carrera?',
                'a' => 'La Licenciatura en Ciencias Jurídicas y Sociales, Abogacía y Notariado incluye cursos clave como: Derecho Civil, Derecho Penal, Derecho Constitucional, Derecho Mercantil, Derecho Laboral, Derecho Administrativo, Derecho Procesal, Derecho Notarial, Filosofía del Derecho, Metodología Jurídica, Sociología Jurídica, Argumentación Jurídica, entre otros. Consulta el Centro de Informaciones o la oficina del Centro UMG Guastatoya.',
                'list' => null,
            ],
            [
                'q' => '¿En qué podrás desempeñarte como Licenciado en Derecho?',
                'a' => 'Podrás trabajar como abogado litigante, asesor jurídico, notario (al completar los requisitos legales), analista legal, defensor público, fiscal, trabajador en juzgados, entidades públicas y privadas, empresas, organizaciones no gubernamentales y en áreas de resolución de conflictos y protección de derechos humanos.',
                'list' => null,
            ],
            [
                'q' => '¿Qué documentos necesito para inscribirme? (recién graduado)',
                'a' => '',
                'list' => [
                    'Constancia de Evaluación de Ubicación.',
                    'Completar Formulario de Nuevo Estudiante.',
                    'Original y fotocopia de DPI o pasaporte.',
                    'Certificación original de Básicos y Diversificado.',
                    'Fotostática de título de 5 x 7 pulgadas (sellado por Contraloría de Cuentas).',
                    'Dos fotografías recientes tamaño cédula.',
                    'Efectuar los pagos de inscripción correspondientes.',
                ],
            ],
            [
                'q' => '¿Qué necesito para traslado de otra universidad?',
                'a' => '',
                'list' => [
                    'Certificación de matrícula.',
                    'Certificación de estudios (ambas de la universidad de procedencia).',
                    'Inversión (costos de preinscripción, inscripción, colegiaturas).',
                    'Costos de inscripción y colegiatura (sujetos a cambios).',
                ],
            ],
        ],
    ],

    'administracion' => [
        'slug' => 'administracion',
        'eyebrow' => 'Administración',
        'title' => 'Administración',
        'subtitle' => 'Licenciatura en Ciencias de la Administración',
        'lead' => 'La Licenciatura en Ciencias de la Administración promueve la excelencia académica mediante un programa acreditado internacionalmente que integra aspectos teóricos y prácticos para la dirección de empresas y la gestión de organizaciones en un entorno cambiante y globalizado.',
        'title_label' => 'Título',
        'degree' => 'Licenciado en Administración de Empresas',
        'duration' => '4 años',
        'hero_image' => 'build/img/about/imgadmi11.jpg',
        'hero_alt' => 'Estudiantes de Ciencias de la Administración en UMG Guastatoya',
        'intro_paragraphs' => [
            'La Licenciatura en Ciencias de la Administración es una carrera que promueve la excelencia académica mediante la implementación de un programa acreditado internacionalmente que integra aspectos teóricos y prácticos para la dirección de empresas y la gestión de organizaciones en el marco de un entorno cambiante y globalizado.',
            'El programa académico es impartido por docentes altamente calificados con experiencia profesional y académica, preparando profesionales capaces de liderar con visión estratégica en el sector empresarial.',
        ],
        'quote' => 'Y conoceréis la verdad y la verdad os hará libres',
        'intro_image' => 'build/img/index/congresoadministracion.jpeg',
        'intro_alt' => 'Congreso académico de Administración UMG',
        'features_eyebrow' => 'UMG Guastatoya',
        'features_title' => 'Desarrolla tu potencial y lidera en tu profesión',
        'features_lead' => 'La carrera de Ciencias de la Administración, guiada por nuestros mentores expertos, puede proporcionar información invaluable para tu desarrollo profesional.',
        'features' => [
            [
                'num' => '01',
                'title' => '¿Qué aprenderás?',
                'body' => 'En esta carrera aprenderás sobre Dirección de Empresas, Requisitos legales de negocios, Contabilidad y Finanzas, Filosofía y Sociología de Negocios, Mercadeo y Proyectos, Economía y Globalización, Operaciones y Logística, Talento Humano y Motivación. Adquirirás conocimientos teóricos y prácticos sobre: Comunicación de Negocios, Análisis de Situaciones Críticas, Gestión de Coaching, Dirección de Equipos, Resolución de Conflictos, Procesos Estadísticos, Toma de Decisiones y Autodominio de Actitud.',
            ],
            [
                'num' => '02',
                'title' => 'Perfil de ingreso',
                'body' => 'El aspirante a la carrera de Administración de Empresas debe tener una inclinación hacia el pensamiento analítico y estratégico. Los aspirantes deben mostrar interés en comprender el funcionamiento de las organizaciones, así como en las dinámicas de gestión y liderazgo empresarial. Se espera que posean habilidades comunicativas y de trabajo en equipo, dado que la colaboración es fundamental en el entorno administrativo. Además, es deseable que tengan una actitud proactiva y adaptabilidad frente a los cambios, habilidades que son cruciales en el mundo empresarial en constante evolución.',
            ],
            [
                'num' => '03',
                'title' => 'Perfil de egreso',
                'body' => 'Al terminar la carrera, el administrador de empresas debe tener el siguiente perfil de egreso: Conocimientos en dirección de empresas, requisitos legales de negocios, contabilidad, finanzas, filosofía y sociología de negocios, mercadeo y proyectos, economía y globalización, operaciones y logística, informática y tecnología, talento humano y motivación. Habilidades en comunicación de negocios, análisis de situaciones críticas, gestión de coaching, dirección de equipos, resolución de conflictos, procesos estadísticos, toma de decisiones, autodominio de actitudes e influencia de valores.',
            ],
        ],
        'topics_eyebrow' => 'Administración de Empresas',
        'topics_title' => 'Administración de Empresas',
        'topics_lead' => 'La gestión estratégica consiste en definir objetivos, analizar el entorno y tomar decisiones que permitan a la empresa mantenerse competitiva. Implica planificar, ejecutar y evaluar acciones que alineen los recursos con la visión de la organización.',
        'topics' => [
            [
                'title' => '¿Por qué estudiar Administración de Empresas?',
                'body' => 'La carrera evoluciona hacia un enfoque digital, innovador y global, incorporando análisis de datos, automatización, liderazgo adaptativo y gestión del cambio como elementos indispensables para enfrentar los nuevos desafíos empresariales.',
                'image' => 'build/img/about/imgadmi11.jpg',
            ],
            [
                'title' => 'El Futuro de Administración de Empresas',
                'body' => 'La carrera evoluciona hacia un enfoque digital, innovador y global, incorporando análisis de datos, automatización, liderazgo adaptativo y gestión del cambio como elementos indispensables para enfrentar los nuevos desafíos empresariales.',
                'image' => 'build/img/about/pabellonUMG.jpeg',
            ],
            [
                'title' => 'Competencias Clave',
                'body' => 'El profesional en Administración de Empresas desarrolla habilidades en liderazgo, toma de decisiones, análisis financiero, gestión de recursos, planificación estratégica y trabajo en equipo, esenciales para dirigir con eficiencia cualquier organización.',
                'image' => 'build/img/index/congresoadministracion.jpeg',
            ],
            [
                'title' => 'Responsabilidad Social',
                'body' => 'La Administración de Empresas promueve una gestión responsable, integrando prácticas éticas y sostenibles en los procesos organizacionales para generar valor económico, social y ambiental dentro de las empresas y su entorno.',
                'image' => 'build/img/index/EstudiantesU.png',
            ],
        ],
        'instructors_title' => 'Nuestros instructores',
        'instructors' => [
            [
                'name' => 'Lic. Jose Humberto Martinez Morales',
                'role' => 'Docente en Administración de Empresas',
                'image' => 'build/img/instructor/docente1admi.jpg',
                'route' => 'detalles-instructor-administracion1',
                'muted' => false,
            ],
            [
                'name' => 'Licda. Debora Anahid Soto Colindres',
                'role' => 'Licenciada en Administración de Empresas',
                'image' => 'build/img/instructor/debora soto1.jpg',
                'route' => 'detalles-instructor-administracion2',
                'muted' => false,
            ],
            [
                'name' => 'Ing Eduardo Hernández',
                'role' => 'Ingeniero en Sistemas de Información y Ciencias de la Computación',
                'image' => 'build/img/instructor/IngSistemasInstructor/IngEduardoHernandezPerfil.jpeg',
                'route' => 'detalles-instructor-administracion3',
                'muted' => false,
            ],
        ],
        'stats' => [
            ['value' => 10, 'label' => 'Oportunidades laborales'],
            ['value' => 6, 'label' => 'Catedráticos'],
            ['value' => 25, 'label' => 'Cursos certificados'],
            ['value' => 8, 'label' => 'Salones de clases'],
        ],
        'faq_image' => 'build/img/about/pabellonUMG.jpeg',
        'faq' => [
            [
                'q' => '¿Por qué elegirnos para tu educación?',
                'a' => 'En la Universidad Mariano Gálvez te formamos como un profesional competitivo en Administración de Empresas, mediante un plan de estudios actualizado y con enfoque práctico. Nuestra formación te prepara para destacar en el ámbito financiero y empresarial.',
                'list' => null,
            ],
            [
                'q' => '¿Qué cursos contiene la carrera?',
                'a' => 'Puede encontrar más detalles en la sección de Centro de Informaciones para revisar el pensum de estudios o bien visitar la oficina de su Centro UMG más cercano.',
                'list' => null,
            ],
            [
                'q' => '¿En qué me podré desempeñar?',
                'a' => 'Podrás desempeñarte en cargos directivos, administrativos, financieros, comerciales o incluso como empresario independiente, gracias a tu formación integral, ética y con visión global.',
                'list' => null,
            ],
            [
                'q' => '¿Qué documentos necesito para inscribirme? (recién graduado)',
                'a' => '',
                'list' => [
                    'Constancia de Evaluación de Ubicación.',
                    'Completar Formulario de Nuevo Estudiante.',
                    'Original y fotocopia de DPI o pasaporte.',
                    'Certificación original de Básicos y Diversificado.',
                    'Fotostática de título de 5 x 7 pulgadas (sellado por Contraloría de Cuentas).',
                    'Dos fotografías recientes tamaño cédula.',
                    'Efectuar los pagos de inscripción correspondientes.',
                ],
            ],
            [
                'q' => '¿Qué necesito para traslado de otra universidad?',
                'a' => '',
                'list' => [
                    'Certificación de matrícula.',
                    'Certificación de estudios (ambas de Universidad de procedencia).',
                    'Inversión (costos de preinscripción, inscripción, colegiaturas).',
                    'Costos de inscripción Q600.00.',
                    'Costos de colegiatura Q560.00 (costos sujetos a cambios).',
                ],
            ],
        ],
    ],

    'criminologia' => [
        'slug' => 'criminologia',
        'eyebrow' => 'Criminología',
        'title' => 'Criminología',
        'subtitle' => 'Licenciatura en Criminología y Política Criminal',
        'lead' => 'Formación integral para criminólogos técnicamente competentes, con enfoque psicológico, sociológico y estratégico en seguridad, prevención del delito y análisis de fenómenos criminales.',
        'title_label' => 'Título',
        'degree' => 'Licenciado en Criminología y Política Criminal',
        'duration' => '5 años',
        'hero_image' => 'build/img/about/iniciocrimi-1.jpg',
        'hero_alt' => 'Estudiantes de Criminología y Política Criminal UMG Guastatoya',
        'intro_paragraphs' => [
            'Es una carrera que promueve la excelencia académica mediante la implementación de un programa integral para la formación de criminólogos, técnica y científicamente competentes en su especialidad.',
            'La carrera tiene un enfoque desde el área psicológica, sociológica y sobre todo estratégica para la seguridad, prevención del delito y detección de formación de fenómenos criminales.',
        ],
        'quote' => 'Y conoceréis la verdad y la verdad os hará libres',
        'intro_image' => 'build/img/index/congresocriminologia.jpeg',
        'intro_alt' => 'Congreso académico de Criminología UMG',
        'features_eyebrow' => 'UMG Guastatoya',
        'features_title' => 'Desarrolla tu potencial y lidera en tu profesión',
        'features_lead' => 'Criminología y Política Criminal te prepara para entender y combatir la conducta criminal con la guía de mentores expertos.',
        'features' => [
            [
                'num' => '01',
                'title' => '¿Qué aprenderás?',
                'body' => 'En esta carrera de Criminología, adquirirás las habilidades teóricas y prácticas para el análisis profundo del delito, aplicando creatividad, habilidad investigativa y lógica crítica para determinar el porqué de un hecho delictivo. El plan de estudios te proporcionará una sólida base en psicología criminal para la comprensión integral del delincuente, junto con el dominio de los aspectos jurídicos esenciales, asegurando el respeto del marco legal en todas las acciones de investigación criminal que realices.',
            ],
            [
                'num' => '02',
                'title' => 'Perfil de ingreso',
                'body' => 'El aspirante ideal a la Licenciatura en Criminología debe poseer una marcada habilidad investigativa y lógica, un profundo pensamiento crítico para el análisis de problemas sociales y delictivos, y un fuerte interés por el comportamiento humano (psicología y sociología). Es esencial que demuestre un sólido compromiso ético y social con la justicia y el marco legal, así como una afinidad por las Ciencias Sociales y Jurídicas, complementada con habilidades de comunicación efectiva para el reporte e interacción profesional.',
            ],
            [
                'num' => '03',
                'title' => 'Perfil de egreso',
                'body' => 'El egresado de Criminología será un profesional capacitado para la investigación, el análisis y la prevención de fenómenos delictivos. Dominará las técnicas de investigación criminal y forense, la perfilación psicológica del delincuente, y aplicará su conocimiento jurídico para diseñar e implementar estrategias de seguridad, prevención y reinserción social que operen de manera ética y dentro del marco legal.',
            ],
        ],
        'topics_eyebrow' => 'Criminología',
        'topics_title' => 'Criminología',
        'topics_lead' => 'La Criminología es la ciencia que estudia el delito, al delincuente y a la víctima, así como los factores que influyen en la conducta criminal. Su propósito es comprender, prevenir y analizar el fenómeno delictivo para contribuir a la seguridad y bienestar de la sociedad.',
        'topics' => [
            [
                'title' => '¿Por qué estudiar criminología?',
                'body' => 'Estudiar criminología permite comprender las causas del delito, apoyar la seguridad ciudadana y trabajar en instituciones de investigación, prevención y justicia. Es una carrera ideal para quienes desean contribuir a una sociedad más justa y segura.',
                'image' => 'build/img/about/iniciocrimi-1.jpg',
            ],
            [
                'title' => 'El Futuro de la Criminología',
                'body' => 'La criminología actual se dirige hacia el uso de tecnologías avanzadas, como análisis forense digital, criminometría y sistemas predictivos. El futuro de la disciplina combina ciencia, tecnología y prevención para comprender mejor las dinámicas del delito.',
                'image' => 'build/img/about/pabellonUMG.jpeg',
            ],
            [
                'title' => 'Competencias Clave',
                'body' => 'Un criminólogo debe dominar la investigación científica, el análisis de conducta delictiva, la elaboración de perfiles criminológicos y la interpretación de datos. También requiere habilidades en mediación, pensamiento crítico y toma de decisiones informada.',
                'image' => 'build/img/index/congresocriminologia.jpeg',
            ],
            [
                'title' => 'Responsabilidad Social',
                'body' => 'La responsabilidad social en criminología implica promover prácticas que fortalezcan la convivencia y reduzcan la violencia. El criminólogo debe actuar con ética, respeto a los derechos humanos y enfoque preventivo para contribuir al bienestar comunitario.',
                'image' => 'build/img/index/EstudiantesU.png',
            ],
        ],
        'instructors_title' => 'Nuestros catedráticos',
        'instructors' => [
            [
                'name' => 'Lic. Carlos Augusto Naavarro Ávila',
                'role' => 'Licenciado en Ciencias Criminológicas Y Criminalísticas',
                'image' => 'build/img/instructor/LicCarlos.png',
                'route' => 'detalles-instructor-criminologia1',
                'muted' => false,
            ],
            [
                'name' => 'Licda. Susan Eunice Galindo Catalan',
                'role' => 'Licenciada en Ciencias Jurídicas y Sociales',
                'image' => 'build/img/instructor/docenteCrimi3.png',
                'route' => 'detalles-instructor-criminologia22',
                'muted' => false,
            ],
            [
                'name' => 'Lic. Roberto Bladimir Roldán Cruz',
                'role' => 'Licenciado en Ciencias Criminología y Criminalística',
                'image' => 'build/img/instructor/2.png',
                'route' => 'detalles-instructor-criminologia3',
                'muted' => false,
            ],
            [
                'name' => 'Lic. Falvio Arturon',
                'role' => 'Licenciado en Ciencias Jurídicas y Sociales',
                'image' => 'build/img/instructor/1.png',
                'route' => 'detalles-instructor-criminologia4',
                'muted' => false,
            ],
            [
                'name' => 'Licda. Debora Anahid Soto Colindres',
                'role' => 'Licenciada en Administración de Empresas',
                'image' => 'build/img/instructor/debora.png',
                'route' => 'detalles-instructor-criminologia5',
                'muted' => false,
            ],
            [
                'name' => 'Inga. Evelyn Raquel Cabrera Sánchez',
                'role' => 'Ingeniera en Sistemas de Información y Ciencias de la Computación',
                'image' => 'build/img/instructor/docenteCrimi4.png',
                'route' => 'detalles-instructor-criminologia6',
                'muted' => false,
            ],
        ],
        'stats' => [
            ['value' => 10, 'label' => 'Oportunidades laborales'],
            ['value' => 6, 'label' => 'Catedráticos'],
            ['value' => 25, 'label' => 'Cursos certificados'],
            ['value' => 8, 'label' => 'Salones de clases'],
        ],
        'faq_image' => 'build/img/about/pabellonUMG.jpeg',
        'faq' => [
            [
                'q' => '¿Por qué elegirnos para tu educación?',
                'a' => 'Porque ofrecemos una formación integral en Criminología, combinando teoría y práctica para comprender, prevenir y analizar el fenómeno delictivo desde un enfoque científico y humano.',
                'list' => null,
            ],
            [
                'q' => '¿Qué cursos contiene la carrera?',
                'a' => 'Incluye materias como Criminología, Criminalística, Derecho Penal, Psicología Criminal y Victimología. Consulta el Centro de Informaciones o bien visitar la oficina del Centro UMG Guastatoya.',
                'list' => null,
            ],
            [
                'q' => '¿En qué podrás desempeñarte como Licenciado en Criminología?',
                'a' => 'Podrás trabajar en instituciones de justicia, seguridad pública, centros de investigación, docencia o asesoría en prevención del delito.',
                'list' => null,
            ],
            [
                'q' => '¿Qué documentos necesito para inscribirme? (recién graduado)',
                'a' => '',
                'list' => [
                    'Constancia de Evaluación de Ubicación.',
                    'Completar Formulario de Nuevo Estudiante.',
                    'Original y fotocopia de DPI o pasaporte.',
                    'Certificación original de Básicos y Diversificado.',
                    'Fotostática de título de 5 x 7 pulgadas (sellado por Contraloría de Cuentas).',
                    'Dos fotografías recientes tamaño cédula.',
                    'Efectuar los pagos de inscripción correspondientes.',
                ],
            ],
            [
                'q' => '¿Qué necesito para traslado de otra universidad?',
                'a' => '',
                'list' => [
                    'Certificación de matrícula.',
                    'Certificación de estudios (ambas de Universidad de procedencia).',
                    'Inversión (costos de preinscripción, inscripción, colegiaturas).',
                    'Costos de inscripción.',
                    'Costos de colegiatura (costos sujetos a cambios).',
                ],
            ],
        ],
    ],

    'sistemas' => [
        'slug' => 'sistemas',
        'eyebrow' => 'Ingeniería en Sistemas',
        'title' => 'Ingeniería en Sistemas',
        'subtitle' => 'Ingeniería en Sistemas y Ciencias de la Computación',
        'lead' => 'Formación de alto nivel para gestionar sistemas de información y desarrollar proyectos tecnológicos alineados a las necesidades de la industria.',
        'title_label' => 'Título',
        'degree' => 'Ingeniero en Sistemas de Información y Ciencias de la Computación',
        'duration' => '5 años',
        'hero_image' => 'build/img/about/aboutIngSistemas/encendido-computadora-portatil-gris.jpeg',
        'hero_alt' => 'Estudiantes de Ingeniería en Sistemas UMG Guastatoya',
        'intro_paragraphs' => [
            'La carrera de Ingeniería en Sistemas de la UMG forma profesionales de alto nivel mediante un plan de estudios innovador, docentes especializados y laboratorios equipados con tecnología actualizada.',
            'Prepárate para gestionar sistemas de información y desarrollar proyectos alineados a las necesidades de la industria tecnológica, con formación teórica y práctica para el entorno global.',
        ],
        'quote' => 'Y conoceréis la verdad y la verdad os hará libres',
        'intro_image' => 'build/img/index/congresosistemas.jpg',
        'intro_alt' => 'Congreso académico de Ingeniería en Sistemas UMG',
        'features_eyebrow' => 'UMG Guastatoya',
        'features_title' => 'Desarrolla tu potencial y lidera en tu profesión',
        'features_lead' => 'Desarrolla tu potencial y lidera en tu profesión con la mentoría de expertos en tecnología que transformarán tu visión profesional.',
        'features' => [
            [
                'num' => '01',
                'title' => '¿Qué aprenderás?',
                'body' => 'Aprenderás a solucionar problemas de forma creativa e innovadora por medio del desarrollo de software, la administración de sistemas informáticos y bases de datos, la implementación de redes y sistemas operativos y el uso avanzado de las telecomunicaciones; adquirirás conocimientos teóricos y prácticos para desempeñarte exitosamente en el desarrollo, implementación y gestión de proyectos tecnológicos para el sector empresarial privado o público en el entorno global.',
            ],
            [
                'num' => '02',
                'title' => 'Perfil de ingreso',
                'body' => 'El aspirante ideal para Ingeniería en Sistemas en la UMG posee sólida base en matemáticas, capacidad de resolver problemas e interés genuino por la tecnología. Debe ser adaptable para aprender lenguajes de programación y mantenerse actualizado en la evolución tecnológica.',
            ],
            [
                'num' => '03',
                'title' => 'Perfil de egreso',
                'body' => 'El ingeniero en Sistemas de la UMG domina fundamentos clave como algoritmos, bases de datos, redes y desarrollo de software, integrando teoría y práctica para diseñar, implementar y gestionar proyectos tecnológicos complejos con calidad y eficiencia.',
            ],
        ],
        'topics_eyebrow' => 'Ingeniería en Sistemas',
        'topics_title' => 'Ingeniería en Sistemas',
        'topics_lead' => 'Es la disciplina que diseña, implementa y optimiza soluciones tecnológicas integrales, combinando conocimientos en software, hardware, redes y gestión de datos para resolver problemas complejos y apoyar la transformación digital.',
        'topics' => [
            [
                'title' => '¿Por qué estudiar Ingeniería en Sistemas?',
                'body' => 'Porque es una de las carreras con mayor demanda, con oportunidades globales en desarrollo de software, ciberseguridad, IA y automatización empresarial.',
                'image' => 'build/img/about/aboutIngSistemas/encendido-computadora-portatil-gris.jpeg',
            ],
            [
                'title' => 'El Futuro de la Ingeniería en Sistemas',
                'body' => 'El crecimiento en IA, ciberseguridad y ciencia de datos posiciona a los ingenieros en sistemas como líderes clave en la transformación digital.',
                'image' => 'build/img/index/congresosistemas.jpg',
            ],
            [
                'title' => 'Competencias Clave',
                'body' => 'Pensamiento crítico, resolución de problemas, diseño de soluciones, comunicación efectiva y gestión de proyectos tecnológicos.',
                'image' => 'build/img/about/pabellonUMG.jpeg',
            ],
            [
                'title' => 'Responsabilidad Social',
                'body' => 'Los ingenieros en sistemas tienen un papel clave en crear soluciones que reduzcan brechas sociales, fomenten la accesibilidad y mejoren la calidad de vida.',
                'image' => 'build/img/index/EstudiantesU.png',
            ],
        ],
        'instructors_title' => 'Nuestros instructores',
        'instructors' => [
            [
                'name' => 'Ing. Oscar Valiente',
                'role' => 'Coordinador de Facultad e Ing en Sistemas de la Información y Ciencias de la Computación (experiencia en CiberSeguridad y Administración de Sistemas).',
                'image' => 'build/img/instructor/IngSistemasInstructor/IngOscarValientePerfil.jpg',
                'route' => 'detalles-instructor-sistemas1',
                'muted' => false,
            ],
            [
                'name' => 'Ing. Richard Ortíz',
                'role' => 'Ing en Sistemas de la Información y Ciencias de la Computación (experiencia en CiberSeguridad).',
                'image' => 'build/img/instructor/IngSistemasInstructor/IngRichardOrtizPerfil.jpeg',
                'route' => 'detalles-instructor-sistemas2',
                'muted' => false,
            ],
            [
                'name' => 'Ing. Otto Ortíz',
                'role' => 'Ing en Sistemas de la Información y Ciencias de la Computación (experiencia en AWS Solutions).',
                'image' => 'build/img/instructor/IngSistemasInstructor/IngOttoOrtizPerfil.jpeg',
                'route' => 'detalles-instructor-sistemas3',
                'muted' => false,
            ],
            [
                'name' => 'Ing. Evelyn Cabrera',
                'role' => 'Ing en Sistemas de la Información y Ciencias de la Computación (experiencia en Dirección y Gestión).',
                'image' => 'build/img/instructor/IngSistemasInstructor/IngRaquelSanchezPerfil.jpeg',
                'route' => 'detalles-instructor-sistemas4',
                'muted' => false,
            ],
            [
                'name' => 'Ing. Teresita Orellana',
                'role' => 'Ing en Sistemas de la Información y Ciencias de la Computación (experiencia en Seguridad Informática).',
                'image' => 'build/img/instructor/IngSistemasInstructor/IngTeresitaOrellanaPerfil.jpeg',
                'route' => 'detalles-instructor-sistemas5',
                'muted' => false,
            ],
            [
                'name' => 'Ing. Eduardo Hernández',
                'role' => 'Ing en Sistemas de la Información y Ciencias de la Computación (experiencia en Seguridad Informática).',
                'image' => 'build/img/instructor/IngSistemasInstructor/IngEduardoHernandezPerfil.jpeg',
                'route' => 'detalles-instructor-sistemas6',
                'muted' => false,
            ],
        ],
        'stats' => [
            ['value' => 10, 'label' => 'Oportunidades laborales'],
            ['value' => 6, 'label' => 'Catedráticos'],
            ['value' => 25, 'label' => 'Cursos certificados'],
            ['value' => 8, 'label' => 'Salones de clases'],
        ],
        'faq_image' => 'build/img/about/pabellonUMG.jpeg',
        'faq' => [
            [
                'q' => '¿Por qué elegirnos para tu educación?',
                'a' => 'En UMG te formamos como un profesional competitivo en tecnología, con un plan de estudios estructurado y con enfoque práctico que te prepara para destacar en el sector tecnológico nacional e internacional.',
                'list' => null,
            ],
            [
                'q' => '¿Qué cursos contiene la carrera?',
                'a' => 'La carrera de Ingeniería en Sistemas integra formación en matemáticas, física y electrónica con asignaturas centrales como programación, bases de datos, redes, inteligencia artificial y seguridad informática. Incluye también cursos de gestión tecnológica, emprendimiento y proyectos de grado para un desarrollo profesional integral. Puede encontrar más información en la sección de Centro de Informaciones o bien visitar la oficina del Centro UMG Guastatoya.',
                'list' => null,
            ],
            [
                'q' => '¿En qué podrás desempeñarte como Ing en Sistemas?',
                'a' => 'Podrás trabajar en desarrollo de software, auditoría de sistemas, administración de infraestructura tecnológica, gestión de redes, dirección de departamentos de TI, gestión de proyectos tecnológicos y seguridad informática, tanto en el sector público como privado.',
                'list' => null,
            ],
            [
                'q' => '¿Qué documentos necesito para inscribirme? (recién graduado)',
                'a' => '',
                'list' => [
                    'Constancia de Evaluación de Ubicación.',
                    'Completar Formulario de Nuevo Estudiante.',
                    'Original y fotocopia de DPI o pasaporte.',
                    'Certificación original de Básicos y Diversificado.',
                    'Fotostática de título de 5 x 7 pulgadas (sellado por Contraloría de Cuentas).',
                    'Dos fotografías recientes tamaño cédula.',
                    'Efectuar los pagos de inscripción correspondientes.',
                ],
            ],
            [
                'q' => '¿Qué necesito para traslado de otra universidad?',
                'a' => '',
                'list' => [
                    'Certificación de matrícula.',
                    'Certificación de estudios (ambas de Universidad de procedencia).',
                    'Inversión (costos de preinscripción, inscripción, colegiaturas).',
                    'Costos de inscripción.',
                    'Costos de colegiatura (costos sujetos a cambios).',
                ],
            ],
        ],
    ],

    'trabajo-social' => [
        'slug' => 'trabajo-social',
        'eyebrow' => 'Trabajo Social',
        'title' => 'Trabajo Social',
        'subtitle' => 'Licenciatura en Trabajo Social',
        'lead' => 'Formación de profesionales especializados para responder a las problemáticas sociales con técnicas y herramientas de gerencia social.',
        'title_label' => 'Título',
        'degree' => 'Licenciado en Trabajo Social.',
        'duration' => '5 años',
        'hero_image' => 'build/img/about/aboutTrabajoSocial/equipo-inicio-TrabajoSocial.jpg',
        'hero_alt' => 'Equipo académico de Trabajo Social UMG Guastatoya',
        'intro_paragraphs' => [
            'La Escuela de Trabajo Social tiene como visión formar profesionales especializados que respondan a las problemáticas sociales, capacitados para aplicar técnicas y herramientas de la gerencia social.',
            'Mediante el fortalecimiento de los conocimientos teóricos de las ciencias sociales y del trabajo social, los estudiantes desarrollan habilidades para gestionar proyectos sociales, promover derechos humanos y trabajar con grupos vulnerables.',
        ],
        'quote' => 'Y conoceréis la verdad y la verdad os hará libres',
        'intro_image' => 'build/img/index/congresotrabajosocial.jpeg',
        'intro_alt' => 'Congreso académico de Trabajo Social UMG',
        'features_eyebrow' => 'UMG Guastatoya',
        'features_title' => 'Desarrolla tu potencial y lidera en tu profesión',
        'features_lead' => 'La carrera de Licenciado en Trabajo Social, guiada por nuestros mentores expertos, puede proporcionar información invaluable para tu desarrollo profesional.',
        'features' => [
            [
                'num' => '01',
                'title' => '¿Qué aprenderás?',
                'body' => 'Ciclos 1° al 4°: Formación teórica en ciencias sociales, fundamentos del trabajo social y el contexto histórico nacional. Ciclos 5° al 6°: Enfoque práctico en la especialidad, desarrollando el razonamiento lógico para analizar problemáticas sociales específicas. Ciclos 7° al 10°: Especialización en gestión e intervención dentro del sistema de protección social.',
            ],
            [
                'num' => '02',
                'title' => 'Perfil de ingreso',
                'body' => 'Posee habilidades avanzadas de comunicación, análisis y pensamiento crítico. Su perfil se distingue por una marcada sensibilidad social para trabajar con grupos vulnerables y adaptarse a entornos de riesgo, actuando siempre con un sólido compromiso ético y respeto por la diversidad cultural y lingüística.',
            ],
            [
                'num' => '03',
                'title' => 'Perfil de egreso',
                'body' => 'Es un profesional comprometido para la promoción del desarrollo y la justicia social, sobre las bases del cumplimiento efectivo de los derechos humanos, la solidaridad y la equidad. Posee conocimientos científicos para comprender las problemáticas que afronta la sociedad. Aplica conocimientos para convertirlos en acciones que contribuyan al bienestar de las personas, familias y grupos vulnerables.',
            ],
        ],
        'topics_eyebrow' => 'Trabajo Social',
        'topics_title' => 'Licenciatura en Trabajo Social',
        'topics_lead' => 'Forma profesionales con sensibilidad social y capacidad de intervención en realidades complejas. A través de un enfoque teórico-práctico, los estudiantes desarrollan habilidades para gestionar proyectos sociales, promover derechos humanos y trabajar con grupos vulnerables, contribuyendo al bienestar colectivo y la transformación social en Guatemala.',
        'topics' => [
            [
                'title' => '¿Por qué estudiar Licenciatura en Trabajo Social?',
                'body' => 'Porque te prepara para ser un agente de cambio en la sociedad, con las herramientas necesarias para intervenir, gestionar y transformar realidades en comunidades, familias e instituciones. A través de un enfoque humanista y metodologías prácticas, desarrollarás la capacidad de promover derechos humanos, impulsar proyectos de impacto social y trabajar con grupos en situación de vulnerabilidad.',
                'image' => 'build/img/about/aboutTrabajoSocial/equipo-inicio-TrabajoSocial.jpg',
            ],
            [
                'title' => 'El Futuro de la Licenciatura en Trabajo Social',
                'body' => 'El campo del trabajo social está evolucionando hacia un enfoque más estratégico y especializado, con una creciente demanda de profesionales capacitados para abordar problemáticas sociales complejas. Los futuros trabajadores sociales no solo intervendrán en situaciones de vulnerabilidad, sino que también liderarán proyectos de innovación social, gestión comunitaria y políticas públicas.',
                'image' => 'build/img/index/congresotrabajosocial.jpeg',
            ],
            [
                'title' => 'Competencias Clave',
                'body' => 'El profesional en Trabajo Social destaca por su capacidad para diseñar, implementar y evaluar intervenciones sociales basadas en el diagnóstico de necesidades comunitarias. Desarrolla habilidades en mediación y resolución de conflictos, acompañamiento psicosocial y gestión de proyectos de impacto colectivo.',
                'image' => 'build/img/about/pabellonUMG.jpeg',
            ],
            [
                'title' => 'Responsabilidad Social',
                'body' => 'La Licenciatura en Trabajo Social forma profesionales cuyo ejercicio profesional está intrínsecamente ligado a la responsabilidad social. A través de su labor, promueven la justicia social, la equidad y el respeto por los derechos humanos, trabajando directamente con comunidades, grupos vulnerables e instituciones para generar condiciones de vida más dignas.',
                'image' => 'build/img/index/EstudiantesU.png',
            ],
        ],
        'instructors_title' => 'Nuestros instructores',
        'instructors' => [
            [
                'name' => 'Lic. Flavio Juárez',
                'role' => 'Licenciado en Pedagogía y Ciencia de la Educación',
                'image' => 'build/img/instructor/TrabajoSocialInstructor/LicFlavioJuarez.jpg',
                'route' => 'detalles-instructor-trabajosocial3',
                'muted' => false,
            ],
            [
                'name' => 'En Construcción...',
                'role' => 'Perfil próximamente',
                'image' => 'build/img/instructor/unknown_user.png',
                'route' => 'detalles-instructor-trabajosocial1',
                'muted' => true,
            ],
            [
                'name' => 'En Construcción...',
                'role' => 'Perfil próximamente',
                'image' => 'build/img/instructor/unknown_user.png',
                'route' => 'detalles-instructor-trabajosocial2',
                'muted' => true,
            ],
        ],
        'stats' => [
            ['value' => 8, 'label' => 'Oportunidades laborales'],
            ['value' => 6, 'label' => 'Catedráticos'],
            ['value' => 25, 'label' => 'Cursos certificados'],
            ['value' => 6, 'label' => 'Salones de clases'],
        ],
        'faq_image' => 'build/img/about/pabellonUMG.jpeg',
        'faq' => [
            [
                'q' => '¿Por qué elegirnos para tu educación?',
                'a' => 'En la Facultad de Trabajo Social de la UMG formamos profesionales con sensibilidad social y capacidad de intervención real. Te prepararemos para transformar vidas y comunidades.',
                'list' => null,
            ],
            [
                'q' => '¿Qué cursos contiene la carrera?',
                'a' => 'La carrera de Trabajo Social integra una formación completa que abarca desde fundamentos filosóficos, históricos y sociales hasta metodologías de intervención individual, familiar, grupal y comunitaria. Incluye cursos como legislación social y derechos humanos, gerencia social, formulación y evaluación de proyectos, investigación científica aplicada, interculturalidad guatemalteca y herramientas prácticas como el Ejercicio Técnico Supervisado y el Trabajo de Graduación, preparando profesionales para responder con ética y eficacia a los desafíos sociales del país. Puede encontrar más información en la sección de Centro de Informaciones o bien visitar la oficina del Centro UMG Guastatoya.',
                'list' => null,
            ],
            [
                'q' => '¿En qué me podré desempeñar?',
                'a' => 'Podrás desempeñarte en la intervención directa con familias y comunidades, gestión de proyectos sociales, promoción y defensa de derechos humanos e investigación y docencia en el ámbito social.',
                'list' => null,
            ],
            [
                'q' => '¿Qué documentos necesito para inscribirme? (recién graduado)',
                'a' => '',
                'list' => [
                    'Constancia de Evaluación de Ubicación.',
                    'Completar Formulario de Nuevo Estudiante.',
                    'Original y fotocopia de DPI o pasaporte.',
                    'Certificación original de Básicos y Diversificado.',
                    'Fotostática de título de 5 x 7 pulgadas (sellado por Contraloría de Cuentas).',
                    'Dos fotografías recientes tamaño cédula.',
                    'Efectuar los pagos de inscripción correspondientes.',
                ],
            ],
            [
                'q' => '¿Qué necesito para traslado de otra universidad?',
                'a' => '',
                'list' => [
                    'Certificación de matrícula.',
                    'Certificación de estudios (ambas de Universidad de procedencia).',
                    'Inversión (costos de preinscripción, inscripción, colegiaturas).',
                    'Costos de inscripción.',
                    'Costos de colegiatura (costos sujetos a cambios).',
                ],
            ],
        ],
    ],

    'auditoria' => [
        'slug' => 'auditoria',
        'eyebrow' => 'Auditoría',
        'title' => 'Auditoría',
        'subtitle' => 'Licenciatura en Contaduría Pública y Auditoría',
        'lead' => 'Formación integral de contadores públicos y auditores con principios éticos, preparados para las exigencias de empresas en un mundo globalizado.',
        'title_label' => 'Título',
        'degree' => 'Licenciado en Contaduría Pública y Auditoría.',
        'duration' => '4 años y medio',
        'hero_image' => 'build/img/about/aboutAuditoria/laptop-paperwork-contabilidad.jpg',
        'hero_alt' => 'Estudiantes de Contaduría Pública y Auditoría UMG Guastatoya',
        'intro_paragraphs' => [
            'Es una carrera que promueve la excelencia académica mediante la implementación de un programa integral para la formación de contadores públicos y auditores con principios éticos y morales preparados para responder a las exigencias de las empresas que necesitan competir en un mundo globalizado.',
            'La carrera es impartida por docentes altamente calificados con experiencia profesional y académica, formando profesionales capaces de gestionar, auditar y analizar la información financiera con responsabilidad y visión estratégica.',
        ],
        'quote' => 'Y conoceréis la verdad y la verdad os hará libres',
        'intro_image' => 'build/img/index/congresoauditoria.jpeg',
        'intro_alt' => 'Congreso académico de Contaduría y Auditoría UMG',
        'features_eyebrow' => 'UMG Guastatoya',
        'features_title' => 'Desarrolla tu potencial y lidera en tu profesión',
        'features_lead' => 'La carrera de Contaduría Pública y Auditoría, guiada por nuestros mentores expertos, puede proporcionar información invaluable para tu desarrollo profesional.',
        'features' => [
            [
                'num' => '01',
                'title' => '¿Qué aprenderás?',
                'body' => 'Esta carrera te prepara para resolver problemas empresariales y tomar decisiones en áreas contables y financieras, utilizando las nuevas tecnologías. Con un sólido enfoque en normativas internacionales, te mantendrás a la vanguardia para atender con profesionalismo a empresas tanto nacionales como internacionales.',
            ],
            [
                'num' => '02',
                'title' => 'Perfil de ingreso',
                'body' => 'Cualquier persona interesada en profundizar sus conocimientos en el área contable y de auditoría, de preferencia con habilidades numéricas, razonamiento crítico y analítico, comprensión lectora, solución de problemas y dedicación. A lo largo de la carrera desarrollará las habilidades para asesorar al Consejo de administración y Gobierno corporativo de la empresa.',
            ],
            [
                'num' => '03',
                'title' => 'Perfil de egreso',
                'body' => 'Profesional ético e independiente, capacitado para desempeñarse en cualquier circunstancia y responder a las demandas de un mundo globalizado. Con sólida formación técnica, está preparado para resolver problemas empresariales y tomar decisiones en los ámbitos contable, financiero, de auditoría y de tecnología.',
            ],
        ],
        'topics_eyebrow' => 'Contaduría y Auditoría',
        'topics_title' => 'Licenciatura en Contaduría y Auditoría',
        'topics_lead' => 'Esta carrera forma profesionales expertos en el análisis, control y gestión de la información financiera de las organizaciones. Los estudiantes desarrollan competencias en contabilidad, auditoría, normativas internacionales y herramientas tecnológicas aplicadas al ámbito tributario y financiero.',
        'topics' => [
            [
                'title' => '¿Por qué estudiar Licenciatura en Contaduría y Auditoría?',
                'body' => 'Esta carrera ofrece una sólida formación en el ámbito financiero y contable, preparando profesionales capaces de gestionar, auditar y analizar la información económica de cualquier organización. Los graduados se integran a un campo laboral estable y con alta demanda, tanto en el sector público como privado, contribuyendo a la transparencia y sostenibilidad de las empresas.',
                'image' => 'build/img/about/aboutAuditoria/laptop-paperwork-contabilidad.jpg',
            ],
            [
                'title' => 'El Futuro de la Lic. en Contaduría y Auditoría',
                'body' => 'Los profesionales de esta disciplina ya no se limitan al registro de operaciones financieras, sino que ahora asumen roles estratégicos en la gestión de riesgos, el análisis de datos y la implementación de sistemas de control automatizados. El futuro de la carrera se orienta hacia la integración de habilidades técnicas y analíticas, preparando a los graduados para liderar en un entorno empresarial cada vez más digitalizado y global.',
                'image' => 'build/img/index/congresoauditoria.jpeg',
            ],
            [
                'title' => 'Competencias Clave',
                'body' => 'El profesional egresado destaca por su capacidad para implementar sistemas de control interno, realizar auditorías financieras y aplicar normativas contables internacionales. Combina habilidades analíticas con un enfoque crítico para la toma de decisiones, gestionando riesgos y optimizando los procesos financieros.',
                'image' => 'build/img/about/pabellonUMG.jpeg',
            ],
            [
                'title' => 'Responsabilidad Social',
                'body' => 'Esta carrera forma profesionales comprometidos con la ética y la responsabilidad social. Los contadores y auditores promueven la transparencia financiera, contribuyen al cumplimiento de obligaciones fiscales y apoyan el desarrollo económico sostenible. Su labor es fundamental para generar confianza en las organizaciones y fomentar prácticas empresariales alineadas con el bienestar social.',
                'image' => 'build/img/index/EstudiantesU.png',
            ],
        ],
        'instructors_title' => 'Nuestros instructores',
        'instructors' => [
            [
                'name' => 'Lic. José Pérez',
                'role' => 'Coordinador de Facultad, Lic en Contaduría Pública y Auditoría.',
                'image' => 'build/img/instructor/AuditoriaInstructor/LicJosePerezPerfil.png',
                'route' => 'detalles-instructor-auditoria1',
                'muted' => false,
            ],
            [
                'name' => 'En Construcción...',
                'role' => 'Perfil próximamente',
                'image' => 'build/img/instructor/unknown_user.png',
                'route' => 'detalles-instructor-auditoria2',
                'muted' => true,
            ],
            [
                'name' => 'En Construcción...',
                'role' => 'Perfil próximamente',
                'image' => 'build/img/instructor/unknown_user.png',
                'route' => 'detalles-instructor-auditoria3',
                'muted' => true,
            ],
        ],
        'stats' => [
            ['value' => 8, 'label' => 'Oportunidades laborales'],
            ['value' => 6, 'label' => 'Catedráticos'],
            ['value' => 25, 'label' => 'Cursos certificados'],
            ['value' => 8, 'label' => 'Salones de clases'],
        ],
        'faq_image' => 'build/img/about/pabellonUMG.jpeg',
        'faq' => [
            [
                'q' => '¿Por qué elegirnos para tu educación?',
                'a' => 'En UMG te formamos como un profesional contable y auditor competitivo, con un plan de estudios actualizado y enfoque práctico que te prepara para destacar en el sector financiero nacional e internacional.',
                'list' => null,
            ],
            [
                'q' => '¿Qué cursos contiene la carrera?',
                'a' => 'La carrera de Contaduría y Auditoría integra una formación completa que abarca contabilidad básica y avanzada, normas internacionales de información financiera y auditoría, legislación mercantil y tributaria, matemática financiera, análisis de estados financieros y gestión de riesgos. Incluye también cursos especializados en costos, auditoría de sistemas, ética profesional y desarrollo de proyectos, preparando profesionales para los desafíos del entorno financiero y empresarial actual. Puede encontrar más información en la sección de Centro de Informaciones o bien visitar la oficina del Centro UMG Guastatoya.',
                'list' => null,
            ],
            [
                'q' => '¿En qué me podré desempeñar?',
                'a' => 'Podrás desempeñarte en posiciones estratégicas como dirección financiera, auditoría interna/externa, consultoría, asesoría tributaria y emprendimiento en el sector contable-financiero.',
                'list' => null,
            ],
            [
                'q' => '¿Qué documentos necesito para inscribirme? (recién graduado)',
                'a' => '',
                'list' => [
                    'Constancia de Evaluación de Ubicación.',
                    'Completar Formulario de Nuevo Estudiante.',
                    'Original y fotocopia de DPI o pasaporte.',
                    'Certificación original de Básicos y Diversificado.',
                    'Fotostática de título de 5 x 7 pulgadas (sellado por Contraloría de Cuentas).',
                    'Dos fotografías recientes tamaño cédula.',
                    'Efectuar los pagos de inscripción correspondientes.',
                ],
            ],
            [
                'q' => '¿Qué necesito para traslado de otra universidad?',
                'a' => '',
                'list' => [
                    'Certificación de matrícula.',
                    'Certificación de estudios (ambas de Universidad de procedencia).',
                    'Inversión (costos de preinscripción, inscripción, colegiaturas).',
                    'Costos de inscripción.',
                    'Costos de colegiatura (costos sujetos a cambios).',
                ],
            ],
        ],
    ],
];
