<?php

return [
    'progress' => [
        ['id' => 'hook', 'label' => 'Inicio'],
        ['id' => 'aprender', 'label' => 'Formación'],
        ['id' => 'ingreso', 'label' => 'Ingreso'],
        ['id' => 'egreso', 'label' => 'Egreso'],
        ['id' => 'comienza', 'label' => 'Admisión'],
    ],

    'scenes' => [
        [
            'id' => 'hook',
            'number' => '01',
            'eyebrow' => 'Facultad de Trabajo Social',
            'title' => '¿Por qué estudiar Trabajo Social?',
            'description' => 'Transforma realidades y construye comunidad. Prepárate para ser agente de cambio con empatía, vocación y compromiso social.',
            'image' => 'images/trabajo-social/8773c2bf-70cf-4999-a83f-12eff7428958.png',
            'image_alt' => 'Docente y estudiantes de Trabajo Social UMG Guastatoya',
            'image_position' => '50% 40%',
            'variant' => 'hook',
            'nav_label' => 'Inicio',
            'points' => [
                'Intervenir y transformar realidades sociales',
                'Promover derechos humanos y equidad',
                'Trabajar con familias y comunidades',
            ],
        ],
        [
            'id' => 'aprender',
            'number' => '02',
            'eyebrow' => 'La carrera en síntesis',
            'title' => '¿Qué aprenderás?',
            'description' => 'De la teoría de las ciencias sociales a la intervención práctica: inclusión, desarrollo comunitario, ética y gestión social.',
            'image' => 'images/trabajo-social/d0cadf79-4f87-4077-bd01-6e1333eb7c6d.png',
            'image_alt' => 'Sesión académica de Trabajo Social en UMG',
            'image_position' => '48% 42%',
            'variant' => 'aprender',
            'nav_label' => 'Formación',
            'words' => ['INCLUIR', 'INTERVENIR', 'TRANSFORMAR'],
            'points' => [
                'Fundamentos de ciencias sociales',
                'Intervención individual, familiar y comunitaria',
                'Gerencia social y proyectos de impacto',
            ],
        ],
        [
            'id' => 'ingreso',
            'number' => '03',
            'eyebrow' => 'UMG Guastatoya',
            'title' => 'Perfil de ingreso',
            'description' => 'Buscamos personas con sensibilidad social, pensamiento crítico y compromiso ético para acompañar a grupos vulnerables.',
            'image' => 'images/trabajo-social/9e726ef6-37cb-435a-852c-ebb3ed380d4b.png',
            'image_alt' => 'Espacio de atención y acompañamiento en Trabajo Social',
            'image_position' => '50% 40%',
            'variant' => 'ingreso',
            'nav_label' => 'Ingreso',
            'points' => [
                'Comunicación y pensamiento crítico',
                'Sensibilidad hacia la diversidad cultural',
                'Vocación de servicio y ética',
            ],
        ],
        [
            'id' => 'egreso',
            'number' => '04',
            'eyebrow' => 'Trabajo Social con propósito',
            'title' => 'Perfil de egreso',
            'description' => 'Egresarás listo para promover desarrollo y justicia social, con acciones que mejoren el bienestar de personas, familias y comunidades.',
            'image' => 'images/trabajo-social/e033ddbb-a7af-434f-9b5e-c5a789a8480a.png',
            'image_alt' => 'Planificación de intervención comunitaria — Trabajo Social UMG',
            'image_position' => '52% 38%',
            'variant' => 'egreso',
            'nav_label' => 'Egreso',
            'points' => [
                'Intervención directa y gestión de proyectos',
                'Defensa de derechos humanos',
                'Investigación y docencia en el ámbito social',
            ],
        ],
        [
            'id' => 'comienza',
            'number' => '05',
            'eyebrow' => 'Admisión abierta',
            'title' => 'Tu historia puede empezar aquí',
            'description' => 'Licenciatura en Trabajo Social. Inscríbete en UMG Guastatoya y construye, junto a otros, un mejor mañana.',
            'image' => 'images/trabajo-social/8773c2bf-70cf-4999-a83f-12eff7428958.png',
            'image_alt' => 'Comunidad de Trabajo Social UMG Guastatoya',
            'image_position' => '45% 42%',
            'variant' => 'comienza',
            'nav_label' => 'Admisión',
            'points' => [
                'Formación teórico-práctica con impacto real',
                'Enfoque humanista y compromiso social',
            ],
            'ctas' => [
                [
                    'label' => 'Ver pensum',
                    'href' => '#umg-trabajo-social-pensum',
                    'style' => 'ghost',
                ],
                [
                    'label' => 'Inscribirme',
                    'href' => 'https://umg.edu.gt/admisiones',
                    'style' => 'primary',
                    'external' => true,
                ],
            ],
        ],
    ],
];
